import type { AccordionState } from "../types";

export type ExportPayload = { fileName: string; mimeType: "text/plain;charset=utf-8"; content: string };

export function buildExportPayload(state: AccordionState, fileName = "accordion") : ExportPayload {
  return { fileName: `${fileName || "accordion"}.jsx`, mimeType: "text/plain;charset=utf-8", content: buildReactCode(state) };
}

export function buildReactCode(state: AccordionState) {
  return [
    "import * as React from \"react\";",
    "",
    "const state = " + JSON.stringify(state, null, 2) + ";",
    "",
    "export default function AccordionComponent() {",
    "  const itemCount = Math.max(1, Math.round(state.itemCount));",
    "  const isMultiple = state.openMode === \"multiple\";",
    "  const initialOpen = state.previewState === \"closed\" ? [] : isMultiple ? [0, 1].filter((index) => index < itemCount) : [0];",
    "  const [openItems, setOpenItems] = React.useState(initialOpen);",
    "  const headingTag = /^h[1-6]$/.test(state.headingLevel) ? state.headingLevel : \"h3\";",
    "",
    "  const toggleItem = (index, disabled) => {",
    "    if (state.disabled || disabled) return;",
    "    setOpenItems((current) => {",
    "      const isOpen = current.includes(index);",
    "      if (isMultiple) return isOpen ? current.filter((item) => item !== index) : [...current, index];",
    "      if (isOpen) return state.collapsible ? [] : current;",
    "      return [index];",
    "    });",
    "  };",
    "",
    "  const renderHeading = (children) => React.createElement(headingTag, { style: { margin: 0 } }, children);",
    "",
    "  return (",
    "    <section",
    "      id={state.id}",
    "      role={state.role}",
    "      aria-label={state.ariaLabel}",
    "      tabIndex={state.disabled ? -1 : state.tabIndex}",
    "      data-open-mode={state.openMode}",
    "      data-disabled-items={state.disabledItems}",
    "      style={{",
    "        width: state.width,",
    "        minHeight: state.height,",
    "        padding: state.padding,",
    "        display: \"grid\",",
    "        gap: state.gap,",
    "        borderRadius: state.radius,",
    "        border: state.borderWidth + \"px solid \" + state.border,",
    "        boxShadow: \"0 \" + Math.round(state.shadow / 3) + \"px \" + state.shadow + \"px rgba(0,0,0,.28)\",",
    "        background: state.background,",
    "        color: state.foreground,",
    "        fontFamily: state.fontFamily,",
    "        opacity: state.disabled ? 0.55 : 1,",
    "      }}",
    "    >",
    "      <div style={{ display: \"grid\", gap: 6 }}>",
    "        <p style={{ margin: 0, color: state.accent, fontSize: 12, fontWeight: 700, letterSpacing: \"0.14em\", textTransform: \"uppercase\" }}>{state.label}</p>",
    "        <h2 style={{ margin: 0, fontSize: state.titleSize, fontWeight: state.fontWeight }}>{state.title}</h2>",
    "        <p style={{ margin: 0, color: state.muted, fontSize: state.bodySize }}>{state.description}</p>",
    "      </div>",
    "      <div style={{ display: \"grid\", gap: Math.max(8, Math.round(state.gap / 1.5)) }}>",
    "        {Array.from({ length: itemCount }, (_, index) => {",
    "          const disabled = index < state.disabledItems;",
    "          const isOpen = openItems.includes(index);",
    "          const buttonId = state.id + \"-trigger-\" + (index + 1);",
    "          const panelId = state.id + \"-panel-\" + (index + 1);",
    "          const button = (",
    "            <button",
    "              type=\"button\"",
    "              id={buttonId}",
    "              aria-expanded={isOpen}",
    "              aria-controls={panelId}",
    "              aria-disabled={disabled || state.disabled}",
    "              disabled={disabled || state.disabled}",
    "              onClick={() => toggleItem(index, disabled)}",
    "              style={{",
    "                width: \"100%\",",
    "                display: \"flex\",",
    "                alignItems: \"center\",",
    "                justifyContent: \"space-between\",",
    "                gap: 12,",
    "                padding: \"14px 16px\",",
    "                borderRadius: Math.max(10, state.radius - 6),",
    "                border: state.borderWidth + \"px solid \" + (isOpen ? state.accent : state.border),",
    "                background: isOpen ? \"color-mix(in oklab, \" + state.accent + \" 18%, transparent)\" : \"transparent\",",
    "                color: state.foreground,",
    "                cursor: disabled || state.disabled ? \"not-allowed\" : \"pointer\",",
    "                font: \"inherit\",",
    "                opacity: disabled ? 0.5 : 1,",
    "                textAlign: \"left\",",
    "              }}",
    "            >",
    "              <span>{state.label} {index + 1}</span>",
    "              <span aria-hidden=\"true\">{state.triggerIcon === \"plus\" ? (isOpen ? \"-\" : \"+\") : (isOpen ? \"up\" : \"down\")}</span>",
    "            </button>",
    "          );",
    "",
    "          return (",
    "            <div key={panelId} data-accordion-item={index + 1}>",
    "              {renderHeading(button)}",
    "              <div",
    "                id={panelId}",
    "                role=\"region\"",
    "                aria-labelledby={buttonId}",
    "                hidden={!isOpen}",
    "                style={{",
    "                  marginTop: isOpen ? 8 : 0,",
    "                  padding: isOpen ? \"12px 16px\" : 0,",
    "                  borderRadius: Math.max(10, state.radius - 8),",
    "                  background: \"rgba(255,255,255,0.06)\",",
    "                  color: state.muted,",
    "                  fontSize: state.bodySize,",
    "                }}",
    "              >",
    "                <p style={{ margin: 0 }}>{state.helper} Item {index + 1} follows the same native button and panel structure used in export.</p>",
    "              </div>",
    "            </div>",
    "          );",
    "        })}",
    "      </div>",
    "    </section>",
    "  );",
    "}",
    "",
  ].join("\n");
}
